### ISSUE TITLE
There is no api "/api/login/oauth/authorize"

### ISSUE THREAD

**Issue by hungtv31** [casdoor/casdoor-java-sdk#25]
Dear,

I tested to integrate use java sdk. It has error 403 when get the token. I checked, it dose not have api: "/api/login/oauth/authorize" Please check again help me.

Thanks!
![image](https://user-images.githubusercontent.com/12571167/180826591-bc8f6bf3-23a1-4e06-a617-7df6d6d4840e.png)

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by seriouszyx** [comment]
@hungtv31 You can read the [docs](https://casdoor.org/docs/how-to-connect/sdk#4-get-and-verify-access-token) for more information. The user clicks the URL created by SDK and is redirected to `https://host:port/login/oauth/authorize?client_id=...`. So you should access this API by GUI rather than SDK. And [here](https://github.com/casdoor/casdoor-spring-boot-example) is a example app  integrated with Casdoor, you can refer to it.

**Comment by hsluoyz** [comment]
Closed as resolved

**Comment by hungtv31** [comment]
Thank for answer!
I set up casdoor in localhost. I run example "https://github.com/casdoor/casdoor-spring-boot-example". It run ok.
I deploy it on server with domain. It run error with error 403. I do not know the reason why?

org.casbin.casdoor.exception.CasdoorAuthException: Cannot get OAuth token.
        at org.casbin.casdoor.service.CasdoorAuthService.getOAuthToken(CasdoorAuthService.java:67)
        at org.casbin.casdoor.springboot.example.controller.AccountController.callback(AccountController.java:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)       
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)     
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://id-dev.onetarget.vn/api/login/oauth/access_token?code=cc49f870cc3bb83102b8&grant_type=authorization_code&client_secret=474d16c8ea2d05bca6faacdced62e2968297b3fb&redirect_uri=https%3A%2F%2Fid-dev.onetarget.vn%2Fapi%2Flogin%2Foauth%2Fauthorize&client_id=902fbc0dc332bd25dc52
        at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:108)
        at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65)
        at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:77)
        at org.casbin.casdoor.service.CasdoorAuthService.getOAuthToken(CasdoorAuthService.java:64)
        ... 51 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://id-dev.onetarget.vn/api/login/oauth/access_token?code=cc49f870cc3bb83102b8&grant_type=authorization_code&client_secret=474d16c8ea2d05bca6faacdced62e2968297b3fb&redirect_uri=https%3A%2F%2Fid-dev.onetarget.vn%2Fapi%2Flogin%2Foauth%2Fauthorize&client_id=902fbc0dc332bd25dc52
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:101)
        ... 54 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://id-dev.onetarget.vn/api/login/oauth/access_token?code=cc49f870cc3bb83102b8&grant_type=authorization_code&client_secret=474d16c8ea2d05bca6faacdced62e2968297b3fb&redirect_uri=https%3A%2F%2Fid-dev.onetarget.vn%2Fapi%2Flogin%2Foauth%2Fauthorize&client_id=902fbc0dc332bd25dc52
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
        at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:97)
        ... 54 more
